#!/bin/bash
subzone=$1
vhost=$(grep -Po '.{1,}(?=.arne-bauters.sb.uclllabs.be)')
mkdir /var/www/html/$1
touch /var/www/html/$1/index.html
echo "<html><body><p>welcome $vhost</p></body></html>" > /var/www/html/$1/index.html
echo -e "<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        ServerName $vhost.arne-bauters.sb.uclllabs.be
        DocumentRoot /var/www/html/$1
        ErrorLog \${APACHE_LOG_DIR}/$vhost-error.log
        CustomLog \${APACHE_LOG_DIR}/$vhost-access.log combined
</VirtualHost>" > /etc/apache2/sites-available/$vhost.arne-bauters.sb.uclllabs.be.conf

a2ensite "$1".conf
systemctl reload apache2

echo "$vhost	IN	A	193.191.177.130" >> /etc/bind/zones/db.arne-bauters.sb.uclllabs.be

SERIAL_NUM=$(grep -oP '\d+(?=\s+; Serial)' /etc/bind/zones/db.arne-bauters.sb.uclllabs.be)
NEW_SERIAL_NUM=$((SERIAL_NUM + 1))
SERIAL_LINE=$(grep -oP '\d+\s+; Serial' /etc/bind/zones/db.arne-bauters.sb.uclllabs.be)                                                                                     SERIALWORD=$(grep -oP '\s+; Serial' /etc/bind/zones/db.arne-bauters.sb.uclllabs.be)
sed -i "s/$SERIAL_LINE/$NEW_SERIAL_NUM$SERIALWORD/g" /etc/bind/zones/db.arne-bauters.sb.uclllabs.be

systemctl reload bind9

