#!/bin/sh

# clone the freeradius git repository
cd /usr/local/src
git clone https://github.com/FreeRADIUS/freeradius-server
cd freeradius-server
git checkout v3.0.x

git pull origin
git log -n 1 --pretty=format:%h
make clean
hash=`git log -n 1 --pretty=format:%h`
./configure \
        --prefix="/usr/local/freeradius-$hash" \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        --disable-developer
#       --with-openssl \                                # default now
make
make install


out=`/usr/local/freeradius-$hash/sbin/radiusd -Cxl stdout $FREERADIUS_OPTIONS`; ret=$?
out=`echo "${out}" | tail -n 1`
if [ "$out" = "Configuration appears to be OK" ];
then

	rm -rf /usr/local/freeradius-$hash/etc/raddb
	unlink /usr/local/freeradius
	ln -s /usr/local/etc/raddb /usr/local/freeradius-$hash/etc/raddb
	ln -s /usr/local/freeradius-$hash /usr/local/freeradius
	/etc/init.d/freeradius stop
	pkill radiusd
	/etc/init.d/freeradius start
	echo "success"
else
	echo "fout"
	exit 1
fi
