---
- hosts: apache
  sudo: yes
  vars:
    http_port: 80
    domain: viesmans.com 
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
       - restart apache2
    
    - name: Create a directory if it does not exist
      file:
        path: /var/www/html/{{ domain }}
        state: directory
 
    - name: create index file for domain
      template: src=index.html dest=/var/www/html/{{ domain }}/index.html 

    - name: apache2 listen on port 80
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
      notify:
       - restart apache2

    - name: create virtual host file
      template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

    - name: apache2 virtualhost on port 80
      lineinfile: dest=/etc/apache2/sites-available/{{ domain }}.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>" state=present
      notify:
        - restart apache2

    - name: a2ensite {{ domain }}
      command: a2ensite {{ domain }}
      args:
        creates: /etc/apache2/sites-enabled/{{ domain }}.conf      
      notify:
       - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
