#! /bin/bash
# /etc/init.d/check_failure_service
### BEGIN INIT INFO
# Provides:          check_failure_service
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

start_check_failure() {
  /usr/local/bin/check_failure_application > /dev/null 2>&1 &
}

stop_check_failure() {
  killall check_failure_application > /dev/null 2>&1 &
}

logger "check_failure_service $1"

case "$1" in
  start)
	start_check_failure;
	;;

  stop)
       	stop_check_failure;
	;;

  restart)
        stop_check_failure;
	sleep 5
	start_check_failure;
	;;

  *)
	echo "Usage: /etc/init.d/check_failure_service {start|stop|restart}"
	exit 1
esac

exit 0
